add documentation for jstor parser
JabRef/user-documentation pull request #319
Opened 2020-10-15 18:00 UTC by joethei

document new fetcher from [#6992](https://github.com/JabRef/jabref/pull/6992)

2020-10-15 19:05 UTC, mlep commented
@Joethel We do not use separated help files for each database anymore. Please, copy-paste the information about the jstor database into https://github.com/JabRef/user-documentation/blob/master/en/collect/import-using-online-bibliographic-database.md

2020-10-18 21:52 UTC, koppor requested changes
Some nitpicks regarding markdown.

2020-10-18 21:52 UTC, koppor commented on en/collect/import-using-online-bibliographic-database.md
> +It is possible to limit the search by adding a field name to the search, as field:"text". The supported fields area:
```suggestion
It is possible to limit the search by adding a field name to the search, such as `field:"text"`. The supported fields are:
```

2020-10-18 21:52 UTC, koppor commented on en/collect/import-using-online-bibliographic-database.md
> +* pt: publication title
```suggestion
* `ti`: The title of the article
* `au`: a author of the article
* `pt`: publication title
```

2020-10-19 14:00 UTC, mlep requested changes

2020-10-22 01:18 UTC, merged