Add explanation of embeddings
JabRef/user-documentation pull request #500
Opened 2024-08-14 11:53 UTC by InAnYan

2024-08-14 15:58 UTC, koppor requested changes
Please no "it's", always long form.

Please: One sentence per line. (In hope that GitBook does that too and does not crash this)

2024-08-14 17:22 UTC, InAnYan commented
Updated

2024-08-15 22:35 UTC, koppor commented
Updated too. @InAnYan I hope, you like.

2024-08-16 14:46 UTC, InAnYan commented on en/ai/README.md
> +They all run "Large Language Models" (LLMs) to process the quests.
quests :)

2024-08-16 14:52 UTC, InAnYan commented
Updated, ready to merge

2024-08-16 15:15 UTC, merged